#!/bin/bash

# Reset directory
folder='apuntes'
cd `dirname $0`
rm -rf ../$folder/*
cp -R ./assets/* ../$folder


 compilingFeed(){

# Getting posts metadata
    sed -n '/^\-\-\-$/,/^\-\-\-$/p' "../markdown-$folder/$1" > ./h.tmp
	grep ': ' "./h.tmp" > ./b.tmp
	sed "s/: /='/g
		s/$/'/g" ./b.tmp > ./v.tmp
	source ./v.tmp

# Create html

    sed '/^\-\-\-$/,/^\-\-\-$/d' "../markdown-$folder/$1" > ./r.tmp
        
	pandoc "./r.tmp" >> ./l.tmp
	cat templates/header.html templates/post-header.html ./l.tmp templates/footer.html > ./.tmp
	sed "s/momotitlemomo/${title}/g
		s/momosubtitlemomo/${subtitle}/g
		s/momodatemomo/${date}/ g" ./.tmp > ../$folder/${f%.md}.html

# Create index feed
	cat templates/feed.html > ./ip.tmp
	sed "s/momotitlemomo/${title}/g
		s/momosubtitlemomo/${subtitle}/g
		s/momolinkmomo/${f%.md}.html/g
		s/momodatemomo/${date}/ g" ./ip.tmp >> ../$folder/index.html

# Delete tmp files with the markdown metadata
    rm ./*.tmp
    rm ./.tmp
}


# Compiling metadata to index.html
cat templates/header.html templates/index-header.html > ./tr.tmp
sed "s/momotitlemomo/Inicio/g" ./tr.tmp > ../$folder/index.html

# Looping md
for f in `ls -t ../markdown-$folder`
do
    compilingFeed $f
done

# Index footer
cat templates/footer.html >> ../$folder/index.html

# Wanna commit?
read -p "Do want to push (y/n) " PUSH

if [ "$PUSH" = "y" ]
then
    echo "Pushing $folder"
    cd ../$folder
    read -p "Insert commit message: " LOL
    git add -A
    git commit -m "$LOL"
    git push

    echo "Pushing markdown-$folder"
    cd ../markdown-$folder
    git add -A
    git commit -m "$LOL"
    git push
fi
