#!/usr/local/bin/bash
# A script to generate a blog from markdown files
# Dependencies: Pandoc
#  

# Reset directory
BLOGPATH=$(pwd)"/${2:-../blog}"
MARKDOWNPATH=$(pwd)"/${1:-../markdown-blog}"
cd `dirname $0`
rm -rf $BLOGPATH/*
cp -R ./assets/* $BLOGPATH
cp CNAME $BLOGPATH


compiling-posts-and-feed(){

# Getting posts metadata
  while read VAREXT
  do
    declare -g "$VAREXT"
  done <<< $(gsed -n '/^\-\-\-$/,/^\-\-\-$/{/^\-\-\-$/d ; s/: /=/g; p}' $MARKDOWNPATH/$1 )
  echo $title
  echo $subtitle
  echo $date
  echo "-------"
  echo "-------"



# Create html 
	gsed "s/momotitlemomo/${title}/g
    s/momosubtitlemomo/${subtitle}/g
		s/momodatemomo/${date}/g" ./templates/header.html ./templates/post-header.html > $BLOGPATH/${1%.md}.html
	pandoc "$MARKDOWNPATH/$1" >> $BLOGPATH/${1%.md}.html
	cat ./templates/footer.html >> $BLOGPATH/${1%.md}.html

# Create index feed
	gsed "s/momotitlemomo/${title}/g
		s/momosubtitlemomo/${subtitle}/g
		s/momolinkmomo/${1%.md}.html/g
		s/momodatemomo/${date}/ g" templates/feed.html >> $BLOGPATH/index.html
}

# Compiling metadata to index.html
gsed "s/momotitlemomo/Inicio/g" templates/header.html templates/index-header.html > $BLOGPATH/index.html
COUNTPAGES=""
# Looping md
for f in `ls -t $MARKDOWNPATH`
do
    compiling-posts-and-feed $f
done

# Index footer
cat templates/footer.html >> $BLOGPATH/index.html

# Wanna commit?
read -p "Do want to push [y/n] " PUSH

if [ "$PUSH" = "y" ]
then
    echo "Pushing $BLOGPATH"
    cd $BLOGPATH
    read -p "Insert commit message: " LOL
    git add -A
    git commit -m "$LOL"
    git push

    echo "Pushing $MARKDOWNPATH"
    cd $MARKDOWNPATH
    git add -A
    git commit -m "$LOL"
    git push
fi
